### ISSUE TITLE
WebJob to inspect service principal secret/certificate expiration

### ISSUE THREAD

**Issue by pschaeflein** [SharePoint/PnP#1352]
Most administrators are quite busy, and would prefer a push notification that secrets/certs are expiring. Leveraging the Tenant Information Portal code, a scheduled web job that pushes message to Group or Email would make a good solution/sample.

**Comment by VesaJuvonen** [comment]
Thanks Paul for putting this down. This would be indeed great enhancement and reusable solution, which would provide direct value for others in community.

**Comment by pschaeflein** [comment]
What would you like as the solution name and location in the repo?

**Comment by VesaJuvonen** [comment]
hmm... There's two options with this. To push this next to Tenatn Information Portal, which makes sense or to keep it as isolated fellow to slightly simplify the use case... so that you can just install this to your tenant and you'd be good to go.

Isolated model would mean that it would be located under the PnP/Solutions (functional as such). Would name this as Governance.AppPrincipal.ExpriationJob - or something similar. 

Opinions and thoughts are more than welcome.

**Comment by pschaeflein** [comment]
Initially, I am planning isolated. So, I'll name it as you suggested in the Solutions folder.
