### ISSUE TITLE
Upload gives a 409 error if tenant default language is not english

### ISSUE THREAD

**Issue by mardahl** [SharePoint/PnP#1419]
Having been unsuccessful in using this tool because of a 409 error. I came to notice that the url used to upload the image doesent exist on my teneant.

It is uploading to /Profile Pictures/ but on my tenant all pictures are in a folder called "Profilbilleder" because the guy who setup our tenant had Danish as his language.

I have renamed the folder via 
https://nordicinsurancesoftware-my.sharepoint.com/_layouts/15/start.aspx#/User%20Photos/Forms/Thumbnails.aspx

And this made the uploader work, dont know if it will break anything else..
Maybe you could have an option in the config to override the picture folder, and instead of throwing and 409 error, notify the admin that the folder doesen't exist, and can be configured etc..

This is from the log file:
27-04-2016 10:22:46 : Begin processing for user user@domain.com
27-04-2016 10:22:46 : Fetching source image: \Servername\Marketing\Employees\ProfilePictures\user.jpg
27-04-2016 10:22:46 : Uploading threes image to SPO, with resizing
27-04-2016 10:22:47 : Uploading small image to /User Photos/Profile Pictures/user_domain_com_SThumb.jpg
27-04-2016 10:22:48 : User Error: Failed to upload thumbnail picture to SPO for user_domain_com The remote server returned an error: (409) Conflict.
27-04-2016 10:22:48 : End processing for user user@domain.com

**Comment by VesaJuvonen** [comment]
thx mardahl, 
could you also pinpoint the actual sample to which this is referring to. Is this the user profile uploader or something else? - Suggestions for language support absolutely make sense.

**Comment by mardahl** [comment]
It is the pictureuploader.exe program. I am unsure what you mean by 'actual sample'.

Med venlig hilsen
Michael Mardahl

**Comment by VesaJuvonen** [comment]
thx mardahl, 
Just needed to ask additional details, since your original issue description did not refer to which of the solutions this comment was around. There's >100 samples/tools in this PnP repository, so details are always good. We'll have a look on this. Most likely there's language dependent attribute or path, which is simply wrong.

**Comment by mardahl** [comment]
Ahh, didnt really look at all the other stuf, was so focused on the profile picture uploader :)

Med venlig hilsen
Michael Mardahl

**Comment by MVOverdijk** [comment]
We ran in the same issue while using the ProfilePictureUploader.exe with a Dutch (nl-NL) tenant. Profile pictures are stored in /User Photos/Profielafbeeldingen/ instead of /User Photos/Profile Pictures/. 
@biste5 solved it by adding the option to set the Picture Path in the ProfilePictureUploader.exe.config. Add the following code to your .config file and set the value corresponding to the locale of your tenant;
`  <appSettings>
    <add key="SPO-PicturesPath" value="/User Photos/Profielafbeeldingen" />
  </appSettings> `


CC: @VesaJuvonen & @mardahl

**Comment by biste5** [comment]
ok @MVOverdijk I'll open a PR very soon with this addition :)

**Comment by VesaJuvonen** [comment]
Issue solved with the provided PR while back, so closing the issue.
