### ISSUE TITLE
PnP Samples Sharepoint 2016 

### ISSUE THREAD

**Issue by djvibe** [SharePoint/PnP#1531]
I am having trouble getting the Samples to compile/work correctly.. will this work in VS2015 and Sharepoint 2016 on premise? or will I need to upgrade them to 2016 somehow?
- PnP Samples - https://github.com/OfficeDev/PnP
  [ ] SharePoint 2016 on Prem

**Comment by VesaJuvonen** [comment]
Hi djvibe, many of the samples do work as such also with SharePoint 2016, but you'll need to update the used assemblies, since in the SharePoint Online does expose some additional properties in the CSOM, which are not supported in on-premises environments. Basic rules are just to update the referenced NuGet package from SharePoint Online to on-premises. Obviously those samples, which reference Azure or other cloud elements, will not work as such in on-premises.
