### ISSUE TITLE
I can create Document Library under Lists folder using PnP script. It should not be allowed.

### ISSUE THREAD

**Issue by dmahendranme** [SharePoint/PnP#1539]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell
#### Category

[#] Bug
[ ] Enhancement
#### Environment

[#] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

PnP script should throw error if anyone creates a Document Library under Lists folder path. 
#### Observed Behavior

PnP script is allowing us to create a Document Library under Lists folder
#### Steps to Reproduce
- Open PowerShell (Obviously with PnP)
- Connect to any site
- Create a list using PnP and mention the template as Document Library and mention the folder path "/Lists/<Document Library name>"

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Hi dmahendranme, since this is possible with native CSOM, it's also possible with PnP operations. Technically we could block that in the PnP side, but it would make the behavior different than with oob capabilities and we don't want to do that with PnP. We do understand that this can cause accidents, but since issue is not really in the PnP side, will close this issue.
