### ISSUE TITLE
Core.RibbonCommands - JavaScript functions not firing in the Modern List UI

### ISSUE THREAD

**Issue by patrickabel** [SharePoint/PnP#1541]
#### Which PnP repository to report the issue?

https://github.com/OfficeDev/PnP/tree/master/Samples/Core.RibbonCommands
#### Category

[X ] Bug
[ ] Enhancement
#### Environment

[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
#### Expected or Desired Behavior

The Core.RibbonCommands PnP sample demonstrates how to execute JavaScript commands based on custom ribbon buttons. However, I am noticing that these commands do not fire correctly when users are in the modern list UI. The buttons themselves are re-oriented into dropdowns but the JavaScript doesn't execute onClick.
#### Observed Behavior

When in the modern UI, JavaScript functions are not executed from custom ribbon buttons.
#### Steps to Reproduce
1. Deploy the Core.RibbonCommands provider hosted add-in
2. Using the add-in, register your custom ribbon commands
3. Navigate to Documents in the classic list UI and click a custom ribbon button
4. Navigate to Documents in the modern list UI and click a custom ribbon button

**Comment by VesaJuvonen** [comment]
Hi patrickabel, this is actually by design in the modern experiences, so we can't really fix this sample, which is targeted for the classic sites. Support in the modern experiences is evolving constantly and we keep on updating following MSDN article based on the released capabilities. https://msdn.microsoft.com/en-us/pnp_articles/modern-experience-customizations-customize-lists-and-libraries
