### ISSUE TITLE
Core.ManageUserCustomAction missing permission in Manifest

### ISSUE THREAD

**Issue by DOliana** [SharePoint/PnP#1550]
I was trying out Core.ManageUserCustomAction sample from the PnP Samples in an O365 environment. I kept on getting "Permission denied" messages while the sample tries to load the custom actions. I figured out that there is a missing permission required in the AppManifest: Tenant => Read.
This should be added in the solution. 
see https://github.com/DOliana/PnP/commit/293a42e9dea93a95f01f7684d643d6661b7fc5cb

**Comment by aaclage** [comment]
Hi DOliana, 

If you access to the url: https://github.com/OfficeDev/PnP/blob/master/Samples/Core.ManageUserCustomAction/CoreManageUserCustomAction/AppManifest.xml
You are able to see the permission for full control was given.
 <AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web" Right="FullControl" />

Can you please re add the permission for the sharepoint-hosted add-in?

thank you,
AL

**Comment by DOliana** [comment]
Hi aaclage,

I don't know what you mean. In my fork the line You mention is still there.

**Comment by VesaJuvonen** [comment]
Hi DOliana,
I just tested this against Office 365 and no tenant level permissions are needed. In general tenant level permissions are not really needed for SP hosted add-ins, since we do not expose any tenant level permissions natively from JavaScript. Tenant operations would require provider hosted add-in setup. I did adjust the project for VS2015 and for SPO with small adjustments, which have been now checked in to the dev branch.  Closing issue at least for now.
