### ISSUE TITLE
Provisioning.SiteCollectionCreation, can't resolve Web.ApplyTheme or Web.MasterUrl

### ISSUE THREAD

**Issue by rrkushner** [SharePoint/PnP#1568]
#### Category
[X] Bug

#### Environment
[X] Office 365 / SharePoint Online

#### Expected or Desired Behavior
Resolve Web.ApplyTheme or Web.MasterUrl

#### Observed Behavior
'Web' does not contain a definition for 'ApplyTheme' and no extension method 'ApplyTheme' accepting a first argument of type 'Web' could be found

'Web' does not contain a definition for 'MasterUrl' and no extension method 'MasterUrl' accepting a first argument of type 'Web' could be found

#### Steps to Reproduce
Open in VS 2015

Note: I do have the listed dependencies:
Microsoft.Online.SharePoint.Client.Tenant
Microsoft.SharePoint.Client.dll
Microsoft.SharePoint.Client.Runtime.dll

What version of these is needed? And which version of .NET?

**Comment by VesaJuvonen** [comment]
Both of the mentioned issues are part of the oob CSOM libraries, so they should resolve regardless of your target environment (SP Online, SP2016 or SP2013). When you pull down samples, you'll need to perform full build on them, so that the NuGet packages are getting installed on your local machine. NuGet packages will then included needed assemblies to your computer.

**Comment by rrkushner** [comment]
I did the full build, but I still got those two error messages, and also
this one:

The type or namespace name 'EventReceivers' does not exist in the namespace
'Microsoft.SharePoint.Client'

Thanks very much for your help!!!

**Comment by VesaJuvonen** [comment]
There is clearly something wrong from environmental perspective with the Visual Studio or computer, since EventReceivers is absolutely valid oob namespace in the CSOM - https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.eventreceivers.aspx. What if you'd create a console application and then add oob CSOM or PnP NuGet package to that manually. These exceptions seems to indicate that you cannot download the packages from Internet, so there could be some restrictions from the machine.

**Comment by VesaJuvonen** [comment]
Since there was no additional response on this since few months, closing this one. Assuming that things are now resolved. If that's not the case, please let us know.
