### ISSUE TITLE
Azure Service Bus operation timeout

### ISSUE THREAD

**Issue by AnoojNair** [SharePoint/PnP#1573]
Hi,

I am currently using this application, and i am facing timeout issues with Azure service bus.Following is the Error

> **This request operation sent to sb://test.servicebus.windows.net/solver/ did not receive a reply within the configured timeout (00:01:00).  The time allotted to this operation may have been a portion of a longer timeout.  This may be because the service is still processing the operation or because the service was unable to send a reply message.  Please consider increasing the operation timeout (by casting the channel/proxy to IContextChannel and setting the OperationTimeout property) and ensure that the service is able to connect to the client.**

How can i resolve this issue, Please advice?

**Comment by VesaJuvonen** [comment]
Hi Anooj,
could you be slightly more specific on which application/sample you are using? - This repository contains roughly 150 samples/solutions, so it would be highly beneficial to understand which solution/sample you are referring to, so that we can test the current setup and see what's going wrong.

thx for the additional details advance.

**Comment by VesaJuvonen** [comment]
Since we did no get any response on this within one month, will close the issue for now. If you have additional details, feel free to submit a new issue, if needed.
