### ISSUE TITLE
The content type “System Page Layout” at “/sites/my-site” is sealed. pnp provisioning engine SharePoint online

### ISSUE THREAD

**Issue by Ragnarok99** [SharePoint/PnP#1574]
####Which PnP repository should you use to report the issue?####
https://github.com/SharePoint/PnP/tree/master/Samples/Provisioning.Framework.Console

#### Category
[X] error

#### Environment
[X ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Observed Behavior
I'm doing some test copying sites with the pnp provisioning engine framework and at ApplyProvisioningTemplate at  step **content type** I get this error The content type "System Page Layout" at "..." is sealed.

Anybody knows what is happening and what can i do?

xml template here: https://mega.nz/#!6A93yIKQ!0jceGpJ37B6w6ZQfahv4H13EK1G0cMcy1qH_Y7WXxgs

**Comment by VesaJuvonen** [comment]
Looking on the template, this is pretty messy site. It's a team site where publishing features have been activated, which really is not a recommended approach, but is indeed supported. This combination has then generated also publishing content types to be exported on the template, which technically would not be needed. You could solve the issue by removing the System Page Layout content type definition from the template manually, but if the flow is fully automated, that's not optimal.

We'll also have a look if we could deal with this Sealed exception in more gracefully, since it's a known exception related on the content type updates - https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.contenttype.update.aspx.

Since this exception is really around the PnP Provisioning Engine, will relocate this issue to right repository (including comments) and close this one here.

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1020
