### ISSUE TITLE
.Net Core Examples should not target .net 451 build

### ISSUE THREAD

**Issue by dmilner321** [SharePoint/PnP#1607]
####Which PnP repository should you use to report the issue?####
- PnP Samples - https://github.com/OfficeDev/PnP

#### Category
[x] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
The 
OfficeDevPnP.Core.Framework.Authentication project Solutions - 
https://github.com/SharePoint/PnP/tree/master/Solutions/AspNetCore.Authentication/src/AspNetCore.Mvc.StarterWeb

This project is intended as an example of how to connect to SharePoint from a .NET Core application. 
My expectations would be that I could utilize this in a NuGet package in an ASP.NET Core SPA application, and utilize this in communicating with SharePoint RESTful services, including the bearer token needed to preserve identity.

 However, in project.json, the target compile for this is .NET 4.5.1.  This negates the usefulness of .NET Core microservices cross-platform advantages and usefulness of containers - Docker/ServiceFabric - one of the most compelling reasons to migrate to .NET Core.

The desired behavior would be to compile the .NET Core project targeting a .NET Core build, not a .NET 4.5.1 build.

#### Observed Behavior
.NET 4.5.1 is targeted due to dependencies.

**Comment by SharePointRadi** [comment]
Hello dmilner321,

Thank you for the well-formatted issue. You are completely correct in your observations and as of now what you have pointed out is the current state.

Compiling for netcoreapp1.0 is an absolute goal of the .NET Core initiative as part of PnP. This is still not possible due to dependent libraries together with the dependencies of the dependencies. We have raised the issue to engineering. 

There's two major parts to it. One of the first key steps is making the CSOM library compile for netcoreapp1.0 first.  The second - PnP has SharePointPnP.IdentityModel which deals with the authentication stuff, but that depends on .NET Framework assemblies for token and claims manipulation. 

It is highlighted as a problem, however it is a huge initiative and we first need updates in other places.

As for now we can run CSOM and PnP in .NET Core applications that compile to net451 only.

**Comment by wysisoft** [comment]
Whats the long term plan on this? Will provider hosted apps ever be able to be 100% dotnetcore? High trust applications being 100% dotnetcore would be really nice too.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
