### ISSUE TITLE
Permission error when installing Content Types with Site Owner

### ISSUE THREAD

**Issue by jpcostach** [SharePoint/PnP#1611]
When executing a provisioning tool to install columns, content types and lists, if we use a Site Collection Admin user, the code executes fine.
Using PnP, we provide an PnP xml with all the information about the columns, content types and lists and execute the following code:
`var clientContext = new ClientContext(Site)
            {
                AuthenticationMode = ClientAuthenticationMode.Default,
                Credentials = new SharePointOnlineCredentials(Username, Password.ToSecureString())
            };
 var web = clientContext.Web;
            clientContext.Load(web, w => w.Title);
            clientContext.ExecuteQueryRetry();
            var provider = new XMLFileSystemTemplateProvider("c:\temp\", "");
            var template = provider.GetTemplate("templatetest.xml");
            var provisioningTemplateApplyingInformation = new ProvisioningTemplateApplyingInformation();
            var connector = new FileSystemConnector("c:\temp\", "");
            template.Connector = connector;
            web.ApplyProvisioningTemplate(template, provisioningTemplateApplyingInformation);`

Executing with a Site Collection Admin, everything runs fine. 
Executing with a Site Owner account, installing the content type fails for 1 or 2 times before it's finally installed. The error is regarding the permissions of the user but after 1 or 2 tries the code executes.

**Comment by VesaJuvonen** [comment]
Hi jpcostach, could you provide slightly more details on which environment this is happening and also what PnP NuGet apckage and version you are using for getting this exception. There's really no specific requirement in the PnP Provisioning Engine for the multiple time execution, so there seems to be something else wrong. If you could provide stack trace and exception details, that would be highly helpful to understand why this goes wrong. Did you apply the template to root site of a site collection or a sub site?

So - ask would be to get environment, PnP NuGet package and exception details. These will help us to reproduce the issue, since unless we can reproduce, we can't really even guess what goes wrong. In general you should be fine with Site Owner permissions.

**Comment by spdevdocs** [comment]
We closed this issue as it had not activity within last 180 days. This is a generic process we have decided to perform for issues, which have not been explicitly marked still to be "work in progress" based on tags. We are performing this cleaning to make sure that old issues that have already been solved (but not closed) or are no longer relevant are cleaned out and make the issues more manageable. If this issue still valid, we would ask you to **open a new issue** and follow the guidance in the issue template related on the recommended location. We do apologize any inconveniences this might cause. Please do remember that issues in the issue lists are also messages for others in the community, so you can also check if you can assist on any of them. *“Sharing is caring!”*
