### ISSUE TITLE
Can't webpack PnP Starter Intranet for Office 365/SharePoint Online

### ISSUE THREAD

**Issue by devfunda3** [SharePoint/PnP#1613]
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
I was installing PnP Starter Intranet for Office 365/SharePoint Online by following the instructions in the md file. (https://github.com/SharePoint/PnP/tree/master/Solutions/Business.StarterIntranet).
When I reached the webpack step:  "Check if everything is OK by running the "webpack" cmd from the ".\app" folder. You shouldn't see any errors here.", it should have not thrown any errors when the webpack command is run.

#### Observed Behavior
webpack version: 1.14.0
typescript version: 2.2.1
Windows 10 64 BIT

Running the webpack command threw up quite a few errors:
![image](https://cloud.githubusercontent.com/assets/26085218/23402214/8c750f98-fda2-11e6-8b34-3ad21809484f.png)
![image](https://cloud.githubusercontent.com/assets/26085218/23402238/9e24cd00-fda2-11e6-8924-972b09c666a3.png)
![image](https://cloud.githubusercontent.com/assets/26085218/23402268/bee32154-fda2-11e6-99f0-2de0045aab77.png)

Package.json snapshot:
![image](https://cloud.githubusercontent.com/assets/26085218/23402118/2987233a-fda2-11e6-9fa3-926ccbdbe7ca.png)

#### Steps to Reproduce
Install the intranet in a similar environment. This would be a great starter sample to start me off on the SharePoint intranet route, since we are building a company intranet on O365\SharePoint Online and I am new to Sharepoint based development.
Thanks in advance.

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by FranckyC** [comment]
@devfunda3 Regarding your error, it is due to the typescript version.  Webpack seems to have trouble with the latest version of TypeScript and I had a similar issue in my environment.

To fix this, open your _package.json_ file and replace the ""`typescript": "^2.1.5`" by  "`typescript": "2.1.5`"" (without the caret) to set a fixed version. Then uninstall Typescript (`npm uninstall typescript`) and reinstall (`npm i`) from the _./app_ folder.

Hope this help!

Let me know.

**Comment by devfunda3** [comment]
Thanks. That worked.

**Comment by eschrader** [comment]
I had this same issue and gave up on this solution completely. I was just going to scrape the masterpage/home layout and homepage HTML and create my own minimal.master and throw it all in. 
I will try this fix when I get around to it, but shouldn't this be updated on GitHub somehow? I almost completely gave up on using this because of the error.

**Comment by FranckyC** [comment]
Hi @eschrader. Did you use the solution from the dev branch? The latest version of the PnP starter intranet hasn't been merged in the master branch yet. I suggest you to get the udpated solution from dev branch and start a fresh installation. Let me know if you encounter issues.
